import HeaderStrip from "../components/header-strip/headerStrip";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Container, Nav, NavDropdown, Navbar, Offcanvas } from "react-bootstrap";


export default function Home() {
 

  return (
    <>
      <Head>
        <title>Appscrip-task-nipun</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderStrip />
        <header className="main-header">

          <div className="mobile-logo-wrap">

          <Navbar  expand="md" className="navbar-main bg-body-primary bg-none">
            <Container  className="custom-container">          
            <Navbar.Toggle className="custom-toggle-button" aria-controls="basic-navbar-nav" />
            <Navbar.Offcanvas
              id={`offcanvasNavbar-expand-md`}
              aria-labelledby={`offcanvasNavbarLabel-expand-md`}
              placement="start"
              className="d-md-none"

            >
              <Offcanvas.Header closeButton>
                <Offcanvas.Title id={`offcanvasNavbarLabel-expand-md`}>
                  <Image
                  src="/header-images/logo.png"
                  alt="logo"
                  width={20}
                  height={20}
                />
                </Offcanvas.Title>
              </Offcanvas.Header>
              <Offcanvas.Body>
                <Nav className="justify-content-end flex-grow-1 pe-3">
                  <Nav.Link href="#action1">Shop</Nav.Link>
                  <Nav.Link href="#action2">Skills</Nav.Link>
                  <Nav.Link href="#action2">Stories</Nav.Link>
                  <Nav.Link href="#action2">About</Nav.Link>
                  <Nav.Link href="#action2">Contact Us</Nav.Link>
                  <Nav.Link href="#action2">
                  <Image
                      src={"icons/profile-icon.svg"}
                      alt="profile"
                      width={20}
                      height={20}
                    />Profile
                  </Nav.Link>
                  <NavDropdown
                    title="ENG"
                    id={`offcanvasNavbarDropdown-expand-md`}
                  >
                    <NavDropdown.Item href="#action4">
                      ENG
                    </NavDropdown.Item>
                    <NavDropdown.Item href="#action4">
                      GER
                    </NavDropdown.Item>
                  </NavDropdown>
                </Nav>
                
              </Offcanvas.Body>
            </Navbar.Offcanvas>
            <Image
                src="/header-images/logo.png"
                alt="logo"
                width={20}
                height={20}
              />
            </Container>
          
          </Navbar>
          <div className="logo-wrap">
            <h1>LOGO</h1>
          </div>
          <div className="service-icons-wrap">
            <Image
              src={"icons/search-icon.svg"}
              alt="search"
              width={20}
              height={20}
            />
            <Image
              src={"icons/heart-icon.svg"}
              alt="heart"
              width={20}
              height={20}
            />
            <Image
              src={"icons/cart-icon.svg"}
              alt="cart"
              width={20}
              height={20}
            />
          </div>

          </div>

          <div className="nav-wrap-desktop">
             
              <Link href="#action1">Shop</Link>
              <Link href="#action2">Skills</Link>
              <Link href="#action2">Stories</Link>
              <Link href="#action2">About</Link>
              <Link href="#action2">Contact Us</Link>

            </div>

             {/* mobile breadcrumb */}
             <div className="mobile-breadcrumb">
            <Link href="#action1">Home</Link>
            <span>|</span>
            <Link href="#action2">Shop</Link>
          </div>

        
        </header>
        
        <div className="container-main">
         
          {/* hero section */}
          <div className="discover-products-wrap">

            <div className="discover-products-wrap--text-box">

            <h1>discover our products</h1>
            <h2>
            Lorem ipsum dolor sit amet consectetur.
             Amet est posuere rhoncus scelerisque.
             Dolor integer scelerisque nibh amet mi ut elementum dolor.
            </h2>

            </div>

            
          </div>
          {/* filter section mobile */}
          <div className="filter-section-mobile">
            <button className="filter-button-wrap">
              Filter
            </button>
            <span>|</span>
            <button className="recommended-button-wrap">
              Recommended
            </button>
          </div>
          {/* product section */}
          <div className="product-card-wrap">
            <div className="product-card">
              <img
                src="/images/product-sample.jpg"
              />
            </div>
            <div className="product-card">
              <img
                src="/images/product-sample.jpg"
              />
            </div>
            <div className="product-card">
              <img
                src="/images/product-sample.jpg"
              />
            </div>
            <div className="product-card">
              <img
                src="/images/product-sample.jpg"
              />
            </div>
            <div className="product-card">
              <img
                src="/images/product-sample.jpg"
              />
            </div>
            <div className="product-card">
              <img
                src="/images/product-sample.jpg"
              />
            </div>
            <div className="product-card">
              <img
                src="/images/product-sample.jpg"
              />
            </div>
            <div className="product-card">
              <img
                src="/images/product-sample.jpg"
              />
            </div>
          </div>

        </div>

        <footer className="footer-main">
          <div className="footer-first-section">
            <div className="subscribe-section">
                <h2>
                Be the first to know
                </h2>
                <p>
                Sign up for updates from mettā muse.
                </p>
                <div className="subscribe-input-wrap">
                  <input placeholder="Enter your e-mail..."/>
                  <button>Subscribe</button>
                </div>
            </div>
            <div className="contact-wrap">
              <div className="call-contact">
                <h1>Contact us</h1>
                <div className="number-email-wrap">
                  <p>+44 221 133 5360</p>
                  <span>
                    <Image
                      src="images/diamond-symbol.svg"
                      width={6}
                      height={6}
                    ></Image>
                  </span>
                  <p>customercare@mettamuse.com</p>
                </div>
                
              </div>

              <div className="currency-wrap">
                <h1>Currency</h1>
                <div className="currency-logo-wrap">
                  <Image
                    src="images/us-flag.svg"
                    width={24}
                    height={24}
                  />

                  <p className='currency-name'>. USD</p>
                 
                </div>
                <p>Transactions will be completed in Euros and a currency reference is available on hover.</p>
              </div>

            </div>
           
          </div>
          <div className="footer-second-section">
            <div className="links-section">
              <div className="meta-muse">
                <h1>mettā muse</h1>
                <ul>
                  <li>About Us</li>
                  <li>Stories</li>
                  <li>Artisans</li>
                  <li>Boutiques</li>
                  <li>About Us</li>
                  <li>Contact Us</li>
                  <li>EU Compliances Docs</li>
                </ul>
              </div>
              <div className="quick-links">
                <h1>Quick Links</h1>
                <ul>
                  <li>Orders & Shipping</li>
                  <li>Join/Login as a Seller</li>
                  <li>Payment & Pricing</li>
                  <li>Return & Refunds</li>
                  <li>FAQs</li>
                  <li>Privacy Policy</li>
                  <li>Terms & Conditions</li>
                </ul>
                
              </div>
            </div> 
            <div className="follow-section">
              <div className="follow-us">
                <h1>Follow us</h1>
                <div className="linked-in-wrap">
                  <Image
                    src="/images/linkedIn.svg"
                    width={32}
                    height={32}
                  />
                   <Image
                    src="/images/instagram.svg"
                    width={32}
                    height={32}
                  />

                </div>
              </div>
              <div className="pay-card-wrap">
                <h1><span>mettā muse</span> Accepts</h1>
                <div className="cards-wrap">
                  <Image
                    src="images/g-pay.svg"
                    width={56}
                    height={35}
                  />
                  <Image
                    src="images/mastercard.svg"
                    width={56}
                    height={35}
                  />
                  <Image
                    src="images/paypal.svg"
                    width={56}
                    height={35}
                  />
                  <Image
                    src="images/amex.svg"
                    width={56}
                    height={35}
                  />
                  <Image
                    src="images/apple-pay.svg"
                    width={56}
                    height={35}
                  />
                   <Image
                    src="images/pay.svg"
                    width={56}
                    height={35}
                  />

                </div>
              </div>
            </div>
          </div>
          <div className="copy-right-wrap">
            <p>
            Copyright © 2023 mettamuse. All rights reserved.
            </p>
          </div>

            
        </footer>
      </main>
    </>
  );
}
